server:
  port: 8081

spring:
  application:
    name: persistence-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/persistence_db
    username: root
    password: Letmein
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: 'create-drop'
      show-sql: true

  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka

system-user:
  email: shadowonline92@gmail.com

security:
  enable-csrf: false
