server:
  port: 8083

spring:
  application:
    name: notification-service

  zipkin:
    base-url: http://zipkin:9411

  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8084/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    user-notification: user.notification.queue
  routing-keys:
    internal-user-notification: internal.user.notification.routing-key