server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://mysql-db:3306/persistence_db
    username: root
    password: Letmein
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  zipkin:
    base-url: http://zipkin:9411

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8084/eureka

security:
  enable-csrf: false