server:
  port: 8084

spring:
  application:
    name: eureka-server


  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8084/eureka